[package]
name = "mousse"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.96"
tokio = "1.43.0"
wayland-client = "0.31.8"
wayland-protocols-wlr = { version = "0.3.6", features = ["client"] }
